# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dab6ef8a1e2e54b45f5aef189a91e83d9953948ddfb24c418d9f948888b549cafed7e44c6a7a84eeaab59eee4b65f7e0c32180c47c5bd482a3aa082653ad1e87

test:
  secret_key_base: 5fa67f04d9f9afc9a7768e1d8aa7f6dff23dc07a42424106958437d89349bd9ea40c366251888d9bbd74c68235e3b521cfb79b7b08c145416ce310325cb9e0fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
